import type { Metadata } from 'next';
import './globals.css';
import { ThemeProvider } from '@/components/common/ThemeProvider';
import { ModeToggle } from '@/components/common/ModeToggle';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body className="relative w-screen h-screen flex flex-col">
        <ThemeProvider>
          <div id="root-portal"></div>
          <ModeToggle />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
